-- Code generated by entlite. DO NOT EDIT.

-- SQLC compatible query definitions

-- Build CRUD operations

-- name: CreateBuild :one
-- re-running the same commit overwrites the row instead of failing on the
-- unique column
INSERT INTO "build" (
  commit_sha,
  branch,
  env,
  status,
  author,
  message,
  duration_ms,
  started_at,
  failed_tests
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT (commit_sha) DO UPDATE SET
  branch = excluded.branch,
  env = excluded.env,
  status = excluded.status,
  author = excluded.author,
  message = excluded.message,
  duration_ms = excluded.duration_ms,
  started_at = excluded.started_at,
  failed_tests = excluded.failed_tests
RETURNING ID;

-- name: CreateBulkBuild :one
-- many rows in one call, the wrapper loops the single row insert
INSERT INTO "build" (
  commit_sha,
  branch,
  env,
  status,
  author,
  message,
  duration_ms,
  started_at,
  failed_tests
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING ID;

-- name: GetBuildByID :one
-- Get() keys on the primary key
SELECT * FROM "build" WHERE ID = ?;

-- name: GetBuildByCommitSha :one
-- GetBy names the columns itself, they have to be unique together
SELECT * FROM "build" WHERE commit_sha = ?;

-- name: ListAllBuild :many
-- no filters, the whole table
SELECT * FROM "build";

-- name: ListBuildByBranch :many
-- a string field becomes an = filter, the caller sends the value
SELECT * FROM "build" WHERE branch = @branch;

-- name: ListBranchStatusHistory :many
-- two fields are two = filters joined by AND, and the sort chain order is
-- the order of the columns in ORDER BY
SELECT * FROM "build" WHERE branch = @branch AND status = @status ORDER BY started_at DESC, commit_sha;

-- name: ListLatestBuilds :many
-- a fixed Limit(10) stays in the sql, so it is not part of the request
SELECT * FROM "build" WHERE branch = @branch ORDER BY started_at DESC LIMIT 10;

-- name: SearchBuilds :many
-- Count() returns how many rows match, counted before Limit cuts the page.
-- Limit() and Offset() take their values from the caller.
SELECT *, COUNT(*) OVER() AS total_size FROM "build" WHERE env = @env AND started_at >= @min_started_at AND started_at <= @max_started_at AND message LIKE @message AND status = @status ORDER BY started_at DESC LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: ListBranches :many
-- one column returns the values, the method gives []string
SELECT DISTINCT branch FROM "build" ORDER BY branch;

-- name: ListEnvBranches :many
-- the same, narrowed by a filter first
SELECT DISTINCT branch FROM "build" WHERE env = @env ORDER BY branch;

-- name: ListBranchStatuses :many
-- several columns dedupe on the tuple and return a row struct
SELECT DISTINCT branch, status FROM "build" ORDER BY branch, status;

-- name: ListBuildsForCleanup :many
-- query level Contracts() drops the rpc, only the database method is generated
SELECT * FROM "build" WHERE started_at >= @min_started_at AND started_at <= @max_started_at;

-- name: UpdateBuild :one
UPDATE "build" SET
  commit_sha = @commit_sha,
  branch = @branch,
  env = @env,
  status = @status,
  author = @author,
  message = @message,
  duration_ms = @duration_ms,
  started_at = @started_at,
  failed_tests = @failed_tests
WHERE ID = @ID
RETURNING *;

-- name: DeleteBuild :exec
DELETE FROM "build" WHERE ID = ?;

-- name: DeleteAllBuild :exec
DELETE FROM "build";

