-- Code generated by entlite. DO NOT EDIT.

-- Table definitions for all entities

-- Build is one run of a ci pipeline, recorded when it finishes
CREATE TABLE IF NOT EXISTS "build"(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  -- unique, so it can be a GetBy key and an Upsert target
  commit_sha TEXT UNIQUE NOT NULL,
  -- these repeat across rows, so Distinct has something to deduplicate
  branch TEXT NOT NULL,
  env TEXT NOT NULL,
  status TEXT NOT NULL,
  author TEXT NOT NULL,
  message TEXT NOT NULL,
  duration_ms INTEGER NOT NULL,
  started_at DATETIME NOT NULL,
  failed_tests INTEGER
);

