-- Code generated by entlite. DO NOT EDIT.

-- SQLC compatible query definitions

-- User CRUD operations

-- name: CreateUser :execlastid
INSERT INTO `user` (
  email,
  name,
  age,
  password,
  api_key,
  is_active,
  login_count,
  rating,
  preferences,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
);
-- name: CreateBulkUser :execlastid
-- re-importing the same users overwrites the row that shares the email
INSERT INTO `user` (
  email,
  name,
  age,
  password,
  api_key,
  is_active,
  login_count,
  rating,
  preferences,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  age = VALUES(age),
  password = VALUES(password),
  is_active = VALUES(is_active),
  login_count = VALUES(login_count),
  rating = VALUES(rating),
  preferences = VALUES(preferences),
  updated_at = VALUES(updated_at);
-- name: GetUserByID :one
SELECT * FROM `user` WHERE ID = ?;

-- name: GetUserByEmail :one
-- Look up a user by email address
SELECT * FROM `user` WHERE email = ?;

-- name: ListAllUser :many
SELECT * FROM `user`;

-- name: ListActive :many
SELECT * FROM `user` WHERE is_active = sqlc.arg('is_active') LIMIT ? OFFSET ?;

-- name: ListUserFilterByAgeName :many
SELECT *, CAST(COUNT(*) OVER() AS SIGNED) AS total_size FROM `user` WHERE age BETWEEN sqlc.arg('min_age') AND sqlc.arg('max_age') AND name LIKE sqlc.arg('name') ORDER BY created_at LIMIT ? OFFSET ?;

-- name: UpdateUser :exec
UPDATE `user` SET
  email = sqlc.arg('email'),
  name = sqlc.arg('name'),
  age = sqlc.arg('age'),
  password = COALESCE(sqlc.narg('password'), password),
  is_active = COALESCE(sqlc.narg('is_active'), is_active),
  login_count = COALESCE(sqlc.narg('login_count'), login_count),
  rating = COALESCE(sqlc.narg('rating'), rating),
  preferences = COALESCE(sqlc.narg('preferences'), preferences),
  updated_at = sqlc.arg('updated_at')
WHERE ID = sqlc.arg('ID');

-- name: DeleteUser :exec
DELETE FROM `user` WHERE ID = ?;

-- name: DeleteAllUser :exec
DELETE FROM `user`;

