-- Code generated by entlite. DO NOT EDIT.

-- Table definitions for all entities

-- user table
CREATE TABLE IF NOT EXISTS `user`(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  -- Full name, e.g. "Jane Doe"
  name VARCHAR(255) NOT NULL,
  age INT,
  password VARCHAR(255) NOT NULL,
  api_key BLOB NOT NULL,
  is_active TINYINT(1) DEFAULT true NOT NULL,
  login_count BIGINT DEFAULT 0 NOT NULL,
  rating DOUBLE DEFAULT 0 NOT NULL,
  -- UI preferences, e.g. {"theme":"dark"}
  preferences JSON NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
CREATE INDEX `idx_user_age_is_active` ON `user` (age, is_active);
CREATE INDEX `idx_user_is_active_created_at` ON `user` (is_active, created_at DESC);
CREATE UNIQUE INDEX `idx_user_name_email` ON `user` (name, email);
CREATE INDEX `idx_users_stats` ON `user` (login_count, rating);

