-- Code generated by entlite. DO NOT EDIT.

-- SQLC compatible query definitions

-- User CRUD operations

-- name: CreateUser :one
INSERT INTO "user" (
  email,
  name,
  age,
  password,
  api_key,
  is_active,
  login_count,
  rating,
  preferences,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
) RETURNING ID;

-- name: CreateBulkUser :one
INSERT INTO "user" (
  email,
  name,
  age,
  password,
  api_key,
  is_active,
  login_count,
  rating,
  preferences,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
) RETURNING ID;

-- name: GetUserByID :one
SELECT * FROM "user" WHERE ID = $1;

-- name: GetUserByEmail :one
SELECT * FROM "user" WHERE email = $1;

-- name: ListAllUser :many
SELECT * FROM "user";

-- name: ListActive :many
SELECT * FROM "user" WHERE is_active = @is_active;

-- name: ListUserFilterByAgeName :many
SELECT * FROM "user" WHERE age BETWEEN @min_age AND @max_age AND name LIKE @name;

-- name: UpdateUser :one
UPDATE "user" SET
  email = @email,
  name = @name,
  age = @age,
  password = COALESCE(sqlc.narg('password'), password),
  is_active = COALESCE(sqlc.narg('is_active'), is_active),
  login_count = COALESCE(sqlc.narg('login_count'), login_count),
  rating = COALESCE(sqlc.narg('rating'), rating),
  preferences = COALESCE(sqlc.narg('preferences'), preferences),
  updated_at = @updated_at
WHERE ID = @ID
RETURNING *;

-- name: DeleteUser :exec
DELETE FROM "user" WHERE ID = $1;

-- name: DeleteAllUser :exec
DELETE FROM "user";

