-- Code generated by entlite. DO NOT EDIT.

-- Table definitions for all entities

-- article table
CREATE TABLE IF NOT EXISTS "article"(
  -- uuid primary key, generated on the server and not part of requests
  id TEXT PRIMARY KEY,
  -- Human/URL identifier, e.g. hello-world
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  subtitle TEXT,
  reading_minutes INT,
  last_viewed_ms BIGINT,
  rating DOUBLE PRECISION,
  cover_image BYTEA,
  published_at TIMESTAMPTZ,
  -- Free-form metadata, e.g. {"og_image":"/cover.png"}
  metadata JSONB,
  is_featured BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

