-- Code generated by entlite. DO NOT EDIT.

-- SQLC compatible query definitions

-- Article CRUD operations

-- name: CreateArticle :execresult
-- re-posting a slug keeps the article that is already there, the caller
-- gets sql.ErrNoRows because nothing was inserted
INSERT INTO `article` (
  id,
  slug,
  title,
  author,
  subtitle,
  reading_minutes,
  last_viewed_ms,
  rating,
  cover_image,
  published_at,
  metadata,
  is_featured,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON DUPLICATE KEY UPDATE slug = slug;
-- name: GetArticleById :one
SELECT * FROM `article` WHERE id = ?;

-- name: GetArticleBySlug :one
SELECT * FROM `article` WHERE slug = ?;

-- name: ListArticleByAuthor :many
SELECT * FROM `article` WHERE author = sqlc.arg('author') LIMIT ? OFFSET ?;

-- name: ListAllArticle :many
SELECT * FROM `article`;

-- name: ListArticleFilterByAuthorIsFeaturedPublishedAtTitle :many
SELECT *, CAST(COUNT(*) OVER() AS SIGNED) AS total_size FROM `article` WHERE author = sqlc.arg('author') AND is_featured = sqlc.arg('is_featured') AND published_at BETWEEN sqlc.arg('min_published_at') AND sqlc.arg('max_published_at') AND title LIKE sqlc.arg('title') ORDER BY published_at LIMIT ? OFFSET ?;

-- name: UpdateArticle :exec
UPDATE `article` SET
  slug = sqlc.arg('slug'),
  title = sqlc.arg('title'),
  author = sqlc.arg('author'),
  subtitle = sqlc.arg('subtitle'),
  reading_minutes = sqlc.arg('reading_minutes'),
  last_viewed_ms = sqlc.arg('last_viewed_ms'),
  rating = sqlc.arg('rating'),
  cover_image = sqlc.arg('cover_image'),
  published_at = sqlc.arg('published_at'),
  metadata = sqlc.arg('metadata'),
  is_featured = COALESCE(sqlc.narg('is_featured'), is_featured),
  updated_at = sqlc.arg('updated_at')
WHERE id = sqlc.arg('id');

-- name: DeleteArticle :exec
DELETE FROM `article` WHERE id = ?;

