-- Code generated by entlite. DO NOT EDIT.

-- Table definitions for all entities

-- article table
CREATE TABLE IF NOT EXISTS `article`(
  -- uuid primary key, generated on the server and not part of requests
  id VARCHAR(36) PRIMARY KEY,
  -- Human/URL identifier, e.g. hello-world
  slug VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255),
  reading_minutes INT,
  last_viewed_ms BIGINT,
  rating DOUBLE,
  cover_image BLOB,
  published_at TIMESTAMP,
  -- Free-form metadata, e.g. {"og_image":"/cover.png"}
  metadata TEXT CHECK (json_valid(metadata)),
  is_featured TINYINT(1) DEFAULT false NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);

