-- Code generated by entlite. DO NOT EDIT.

-- SQLC compatible query definitions

-- Reading CRUD operations

-- name: CreateReading :one
INSERT INTO "reading" (
  sensor_id,
  value,
  quality,
  flagged,
  recorded_at,
  created_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id;

-- name: GetReadingById :one
SELECT * FROM "reading" WHERE id = ?;

-- name: ListReadingBySensorId :many
SELECT * FROM "reading" WHERE sensor_id = @sensor_id LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: ListReadingFilterBySensorIdRecordedAtFlagged :many
SELECT *, COUNT(*) OVER() AS total_size FROM "reading" WHERE sensor_id = @sensor_id AND recorded_at >= @min_recorded_at AND recorded_at <= @max_recorded_at AND flagged = @flagged ORDER BY recorded_at LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: UpdateReading :one
UPDATE "reading" SET
  sensor_id = @sensor_id,
  value = @value,
  quality = @quality,
  flagged = COALESCE(sqlc.narg('flagged'), flagged),
  recorded_at = @recorded_at
WHERE id = @id
RETURNING *;

-- name: DeleteReading :exec
DELETE FROM "reading" WHERE id = ?;

-- Sensor CRUD operations

-- name: CreateSensor :one
INSERT INTO "sensor" (
  code,
  label,
  kind,
  unit,
  location,
  active,
  firmware,
  sample_rate_ms,
  installed_at,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
) RETURNING id;

-- name: GetSensorById :one
SELECT * FROM "sensor" WHERE id = ?;

-- name: GetSensorByCode :one
-- Look up a sensor by its hardware code
SELECT * FROM "sensor" WHERE code = ?;

-- name: ListSensorFilterByLabelKindActive :many
SELECT *, COUNT(*) OVER() AS total_size FROM "sensor" WHERE label LIKE @label AND kind = @kind AND active = @active ORDER BY installed_at LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: UpdateSensor :one
UPDATE "sensor" SET
  code = @code,
  label = @label,
  kind = @kind,
  unit = @unit,
  location = @location,
  active = COALESCE(sqlc.narg('active'), active),
  firmware = COALESCE(sqlc.narg('firmware'), firmware),
  sample_rate_ms = COALESCE(sqlc.narg('sample_rate_ms'), sample_rate_ms),
  updated_at = @updated_at
WHERE id = @id
RETURNING *;

-- name: DeleteSensor :exec
DELETE FROM "sensor" WHERE id = ?;

