package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/guntisdev/entlite/internal/util"
)

func TestSqlcWrapCommand(t *testing.T) {
	tmpDir := t.TempDir()

	schemaDir := filepath.Join(tmpDir, "ent", "schema")
	logicDir := filepath.Join(tmpDir, "ent", "logic")
	inputDir := filepath.Join(tmpDir, "ent", "gen", "db", "internal")
	outputDir := filepath.Join(tmpDir, "ent", "gen", "db")

	if err := os.MkdirAll(schemaDir, 0755); err != nil {
		t.Fatalf("Failed to create schema directory: %v", err)
	}

	if err := os.MkdirAll(logicDir, 0755); err != nil {
		t.Fatalf("Failed to create logic directory: %v", err)
	}

	if err := os.MkdirAll(inputDir, 0755); err != nil {
		t.Fatalf("Failed to create input directory: %v", err)
	}

	// Write common test input files
	writeTestGoMod(t, tmpDir)
	writeTestUserSchema(t, schemaDir)
	writeTestLogic(t, logicDir)

	sqlcQueriesContent := `// Code generated by sqlc. DO NOT EDIT.
package internal

import (
	"context"
	"database/sql"
	"time"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

const createUser = ` + "`-- name: CreateUser :one\nINSERT INTO users (email, name, age, password, score, uuid, is_admin, api_key, last_login_ms, created_at, updated_at)\nVALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)\nRETURNING id\n`" + `

type CreateUserParams struct {
	Email       string
	Name        string
	Age         *int32
	Password    string
	Score       float64
	Uuid        string
	IsAdmin     bool
	ApiKey      []byte
	LastLoginMs int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID          int64
	Email       string
	Name        string
	Age         *int32
	Password    string
	Score       float64
	Uuid        string
	IsAdmin     bool
	ApiKey      []byte
	LastLoginMs int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Age,
		arg.Password,
		arg.Score,
		arg.Uuid,
		arg.IsAdmin,
		arg.ApiKey,
		arg.LastLoginMs,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i int64
	err := row.Scan(&i)
	return i, err
}

const updateUser = ` + "`-- name: UpdateUser :one\nUPDATE users\nSET email = $2, name = $3, age = $4, password = COALESCE(sqlc.narg('password'), password), score = $5, is_admin = $6, api_key = $7, last_login_ms = $8, updated_at = $9\nWHERE id = $1\nRETURNING id, email, name, age, password, score, uuid, is_admin, api_key, last_login_ms, created_at, updated_at\n`" + `

type UpdateUserParams struct {
	ID          int64
	Email       string
	Name        string
	Age         *int64
	Password    *string
	Score       float64
	IsAdmin     int64
	ApiKey      []byte
	LastLoginMs int64
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Age,
		arg.Password,
		arg.Score,
		arg.IsAdmin,
		arg.ApiKey,
		arg.LastLoginMs,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Age,
		&i.Password,
		&i.Score,
		&i.Uuid,
		&i.IsAdmin,
		&i.ApiKey,
		&i.LastLoginMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}`

	sqlcQueriesPath := filepath.Join(inputDir, "queries.sql.go")
	if err := os.WriteFile(sqlcQueriesPath, []byte(sqlcQueriesContent), 0644); err != nil {
		t.Fatalf("Failed to write sqlc queries file: %v", err)
	}

	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current directory: %v", err)
	}
	if err := os.Chdir(filepath.Join(tmpDir, "ent")); err != nil {
		t.Fatalf("Failed to change directory: %v", err)
	}
	defer os.Chdir(originalDir)

	sqlcYamlContent := `version: "2"
sql:
  - schema: "contract/sqlc/schema.sql"
    queries: "contract/sqlc/queries.sql"
    engine: "sqlite"
    gen:
      go:
        package: "internal"
        out: "gen/db/internal"
        emit_json_tags: true
`
	sqlcYamlPath := filepath.Join(tmpDir, "ent", "sqlc.yaml")
	if err := os.WriteFile(sqlcYamlPath, []byte(sqlcYamlContent), 0644); err != nil {
		t.Fatalf("Failed to write sqlc.yaml file: %v", err)
	}

	sqlcWrapCommand()

	outputPath := filepath.Join(outputDir, "queries.sql.go")
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Fatalf("Expected queries.sql.go was not created at %s", outputPath)
	}

	actualContent, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read generated queries.sql.go: %v", err)
	}

	expectedContent := `package db

import (
	"context"
	"fmt"
	"github.com/guntisdev/entlite/examples/01-basic-entity/ent/logic"
	"time"
	internal "github.com/guntisdev/entlite/examples/01-basic-entity/ent/gen/db/internal"
)

type DBTX = internal.DBTX
func New(db DBTX) *Queries { return (*Queries)(internal.New(db)) }
type Queries internal.Queries
type CreateUserParams struct {
	Email string
	Name string
	Age *int32
	Password string
	Score float64
	Uuid *string
	IsAdmin bool
	ApiKey *[]byte
	LastLoginMs int64
}

type User = internal.User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	if !logic.StartsWithCapital(arg.Name) {
		return 0, fmt.Errorf("Failed create: incorrect value for 'User' in field 'name', validated by 'logic.StartsWithCapital'")
	}
	internalArg := internal.CreateUserParams{
		Email: arg.Email,
		Name: arg.Name,
		Age: IntPtrConvert[int32, int64](arg.Age),
		Password: arg.Password,
		Score: arg.Score,
		Uuid: OptionalWithFallback(arg.Uuid, logic.GetUuidStr()),
		IsAdmin: SQLiteBoolToInt(arg.IsAdmin),
		ApiKey: OptionalWithFallback(arg.ApiKey, logic.GenerateAPIKey()),
		LastLoginMs: arg.LastLoginMs,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	id, err := (*internal.Queries)(q).CreateUser(ctx, internalArg)
	return IntConvert[int64, int32](id), err
}

type UpdateUserParams struct {
	ID int32
	Email string
	Name string
	Age *int32
	Password *string
	Score float64
	IsAdmin bool
	ApiKey *[]byte
	LastLoginMs int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	if !logic.StartsWithCapital(arg.Name) {
		return nil, fmt.Errorf("Failed update: incorrect value for 'User' in field 'name', validated by 'logic.StartsWithCapital'")
	}
	internalArg := internal.UpdateUserParams{
		ID: IntConvert[int32, int64](arg.ID),
		Email: arg.Email,
		Name: arg.Name,
		Age: IntPtrConvert[int32, int64](arg.Age),
		Password: arg.Password,
		Score: arg.Score,
		IsAdmin: SQLiteBoolToInt(arg.IsAdmin),
		ApiKey: OptionalWithFallback(arg.ApiKey, logic.GenerateAPIKey()),
		LastLoginMs: arg.LastLoginMs,
		UpdatedAt: time.Now(),
	}

	dbUser, err := (*internal.Queries)(q).UpdateUser(ctx, internalArg)
	if err != nil {
		return nil, err
	}
	return UserFromSQL(&dbUser), nil
}`

	if d := util.Diff(expectedContent, string(actualContent)); d != "" {
		t.Errorf("queries.sql.go content mismatch (-expected +actual):\n%s", d)
	}
}
