package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/guntisdev/entlite/internal/util"
)

func TestSqlcWrapCommand(t *testing.T) {
	tmpDir := t.TempDir()

	schemaDir := filepath.Join(tmpDir, "ent", "schema")
	logicDir := filepath.Join(tmpDir, "ent", "logic")
	inputDir := filepath.Join(tmpDir, "ent", "gen", "db", "internal")
	outputDir := filepath.Join(tmpDir, "ent", "gen", "db")

	if err := os.MkdirAll(schemaDir, 0755); err != nil {
		t.Fatalf("Failed to create schema directory: %v", err)
	}

	if err := os.MkdirAll(logicDir, 0755); err != nil {
		t.Fatalf("Failed to create logic directory: %v", err)
	}

	if err := os.MkdirAll(inputDir, 0755); err != nil {
		t.Fatalf("Failed to create input directory: %v", err)
	}

	// Write common test input files
	writeTestGoMod(t, tmpDir)
	writeTestUserSchema(t, schemaDir)
	writeTestLogic(t, logicDir)

	sqlcQueriesContent := `// Code generated by sqlc. DO NOT EDIT.
package internal

import (
	"context"
	"database/sql"
	"time"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

const createUser = ` + "`-- name: CreateUser :one\nINSERT INTO users (email, name, age, score, uuid, is_admin, api_key, created_at, updated_at)\nVALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)\nRETURNING id, email, name, age, score, uuid, is_admin, api_key, created_at, updated_at\n`" + `

type CreateUserParams struct {
	Email     string
	Name      string
	Age       *int32
	Score     float64
	Uuid      string
	IsAdmin   bool
	ApiKey    []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Email     string
	Name      string
	Age       *int32
	Score     float64
	Uuid      string
	IsAdmin   bool
	ApiKey    []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Age,
		arg.Score,
		arg.Uuid,
		arg.IsAdmin,
		arg.ApiKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Age,
		&i.Score,
		&i.Uuid,
		&i.IsAdmin,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = ` + "`-- name: UpdateUser :one\nUPDATE users\nSET email = $2, name = $3, age = $4, score = $5, is_admin = $6, updated_at = $7\nWHERE id = $1\nRETURNING id, email, name, age, score, uuid, is_admin, api_key, created_at, updated_at\n`" + `

type UpdateUserParams struct {
	ID        int64
	Email     string
	Name      string
	Age       int32
	Score     float64
	IsAdmin   bool
	UpdatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Age,
		arg.Score,
		arg.IsAdmin,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Age,
		&i.Score,
		&i.Uuid,
		&i.IsAdmin,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}`

	sqlcQueriesPath := filepath.Join(inputDir, "queries.sql.go")
	if err := os.WriteFile(sqlcQueriesPath, []byte(sqlcQueriesContent), 0644); err != nil {
		t.Fatalf("Failed to write sqlc queries file: %v", err)
	}

	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current directory: %v", err)
	}
	if err := os.Chdir(filepath.Join(tmpDir, "ent")); err != nil {
		t.Fatalf("Failed to change directory: %v", err)
	}
	defer os.Chdir(originalDir)

	sqlcYamlContent := `version: "2"
sql:
  - schema: "contract/sqlc/schema.sql"
    queries: "contract/sqlc/queries.sql"
    engine: "sqlite"
    gen:
      go:
        package: "internal"
        out: "gen/db/internal"
        emit_json_tags: true
`
	sqlcYamlPath := filepath.Join(tmpDir, "ent", "sqlc.yaml")
	if err := os.WriteFile(sqlcYamlPath, []byte(sqlcYamlContent), 0644); err != nil {
		t.Fatalf("Failed to write sqlc.yaml file: %v", err)
	}

	sqlcWrapCommand()

	outputPath := filepath.Join(outputDir, "queries.sql.go")
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Fatalf("Expected queries.sql.go was not created at %s", outputPath)
	}

	actualContent, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read generated queries.sql.go: %v", err)
	}

	expectedContent := `package db

import (
	"context"
	"database/sql"
	"fmt"
	"math"
	"google.golang.org/protobuf/types/known/timestamppb"
	"github.com/guntisdev/entlite/examples/01-basic-entity/ent/logic"
	"time"
	internal "github.com/guntisdev/entlite/examples/01-basic-entity/ent/gen/db/internal"
)

type DBTX = internal.DBTX
func New(db DBTX) *Queries { return (*Queries)(internal.New(db)) }
type Queries internal.Queries
type CreateUserParams struct {
	Email string
	Name string
	Age *int32
	Score float64
	IsAdmin bool
}

type User = internal.User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	if !logic.StartsWithCapital(arg.Name) {
		return 0, fmt.Errorf("Failed create: incorrect value for 'User' in field 'name', validated by 'logic.StartsWithCapital'")
	}
	internalArg := internal.CreateUserParams{
		Email: arg.Email,
		Name: arg.Name,
		Age: SQLitePtrInt32ToNullInt64(arg.Age),
		Score: arg.Score,
		Uuid: logic.GetUuidStr(),
		IsAdmin: SQLiteBoolToInt(arg.IsAdmin),
		ApiKey: logic.GenerateAPIKey(),
		LastLoginMs: arg.LastLoginMs,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	id, err := (*internal.Queries)(q).CreateUser(ctx, internalArg)
	return SQLiteInt64ToInt32(id), err
}

type UpdateUserParams struct {
	ID int32
	Email string
	Name string
	Age *int32
	Score float64
	IsAdmin bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	if !logic.StartsWithCapital(arg.Name) {
		return nil, fmt.Errorf("Failed update: incorrect value for 'User' in field 'name', validated by 'logic.StartsWithCapital'")
	}
	internalArg := internal.UpdateUserParams{
		ID: SQLiteInt32ToInt64(arg.ID),
		Email: arg.Email,
		Name: arg.Name,
		Age: SQLitePtrInt32ToNullInt64(arg.Age),
		Score: arg.Score,
		IsAdmin: SQLiteBoolToInt(arg.IsAdmin),
		LastLoginMs: arg.LastLoginMs,
		UpdatedAt: time.Now(),
	}

	dbUser, err := (*internal.Queries)(q).UpdateUser(ctx, internalArg)
	if err != nil {
		return nil, err
	}
	return UserFromSQL(&dbUser), nil
}


// TimeToProto converts time.Time to timestamppb.Timestamp pointer
func TimeToProto(t time.Time) *timestamppb.Timestamp {
	return timestamppb.New(t)
}

// Note: If the pointer is nil, it returns a zero time.Time{}
func ProtoToTime(t *timestamppb.Timestamp) time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.AsTime()
}

// --- Int32 Converters ---
func NullInt32ToPtr(n sql.NullInt32) *int32 {
	if !n.Valid { return nil }
	return &n.Int32
}

func PtrToNullInt32(i *int32) sql.NullInt32 {
	if i == nil {
		return sql.NullInt32{Valid: false}
	}
	return sql.NullInt32{ Int32: *i, Valid: true }
}

// --- Int64 Converters ---
func NullInt64ToPtr(n sql.NullInt64) *int64 {
	if !n.Valid { return nil }
	return &n.Int64
}

func PtrToNullInt64(i *int64) sql.NullInt64 {
	if i == nil {
		return sql.NullInt64{Valid: false}
	}
	return sql.NullInt64{ Int64: *i, Valid: true }
}

// --- Float64 Converters ---
func NullFloat64ToPtr(n sql.NullFloat64) *float64 {
	if !n.Valid { return nil }
	return &n.Float64
}

func PtrToNullFloat64(i *float64) sql.NullFloat64 {
	if i == nil {
		return sql.NullFloat64{Valid: false}
	}
	return sql.NullFloat64{ Float64: *i, Valid: true }
}

// --- String Converters ---
func NullStringToPtr(n sql.NullString) *string {
	if !n.Valid { return nil }
	return &n.String
}

func PtrToNullString(i *string) sql.NullString {
	if i == nil {
		return sql.NullString{Valid: false}
	}
	return sql.NullString{ String: *i, Valid: true }
}

// --- Bool Converters ---
func NullBoolToPtr(n sql.NullBool) *bool {
	if !n.Valid { return nil }
	return &n.Bool
}

func PtrToNullBool(i *bool) sql.NullBool {
	if i == nil {
		return sql.NullBool{Valid: false}
	}
	return sql.NullBool{ Bool: *i, Valid: true }
}

// --- Time Converters ---
func NullTimeToProto(n sql.NullTime) *timestamppb.Timestamp {
	if !n.Valid {
		return nil
	}
	return timestamppb.New(n.Time)
}

func ProtoToNullTime(t *timestamppb.Timestamp) sql.NullTime {
	if t == nil {
		return sql.NullTime{Valid: false}
	}
	return sql.NullTime{
		Time:  t.AsTime(),
		Valid: true,
	}
}

// --- Bytes Converters ---
func NullBytesToPtr(b []byte) *[]byte {
    if b == nil { return nil }
    return &b
}

func PtrToNullBytes(b *[]byte) []byte {
    if b == nil { return nil }
    return *b
}

// --- SQLite bool converters ---
func SQLiteIntToBool(i int64) bool {
    switch i {
    case 0:
        return false
    case 1:
        return true
    default:
        panic("Unable convert sqlite int to bool")
    }
}

func SQLiteBoolToInt(b bool) int64 {
    if b {
        return 1
    } else {
        return 0
    }
}

// --- SQLite int converters int32 - int64 ---
func SQLiteInt64ToInt32(n int64) int32 {
    if n < math.MinInt32 || n > math.MaxInt32 {
		panic("Unable convert sqlite int64 to int32")
	}
	return int32(n)
}

func SQLiteInt32ToInt64(n int32) int64 {
    return int64(n)
}

// --- SQLite null-int converters int32 - int64 ---
func SQLiteNullInt64ToPtrInt32(n sql.NullInt64) *int32 {
	if !n.Valid { return nil }
    v := SQLiteInt64ToInt32(n.Int64)
	return &v
}

func SQLitePtrInt32ToNullInt64(i *int32) sql.NullInt64 {
    if i == nil {
		return sql.NullInt64{Valid: false}
	}
	return sql.NullInt64{ Int64: int64(*i), Valid: true }
}`

	if d := util.Diff(expectedContent, string(actualContent)); d != "" {
		t.Errorf("queries.sql.go content mismatch (-expected +actual):\n%s", d)
	}
}
