package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/guntisdev/entlite/internal/util"
)

func TestSqlcWrapCommand(t *testing.T) {
	tmpDir := t.TempDir()

	schemaDir := filepath.Join(tmpDir, "ent", "schema")
	logicDir := filepath.Join(tmpDir, "ent", "logic")
	inputDir := filepath.Join(tmpDir, "ent", "gen", "db")
	outputDir := filepath.Join(tmpDir, "ent", "gen", "dbwrap")

	if err := os.MkdirAll(schemaDir, 0755); err != nil {
		t.Fatalf("Failed to create schema directory: %v", err)
	}

	if err := os.MkdirAll(logicDir, 0755); err != nil {
		t.Fatalf("Failed to create logic directory: %v", err)
	}

	if err := os.MkdirAll(inputDir, 0755); err != nil {
		t.Fatalf("Failed to create input directory: %v", err)
	}

	// Write common test input files
	writeTestGoMod(t, tmpDir)
	writeTestUserSchema(t, schemaDir)
	writeTestLogic(t, logicDir)

	sqlcQueriesContent := `// Code generated by sqlc. DO NOT EDIT.
package db

import (
	"context"
	"database/sql"
	"time"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

const createUser = ` + "`-- name: CreateUser :one\nINSERT INTO users (email, name, age, score, uuid, is_admin, api_key, created_at, updated_at)\nVALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)\nRETURNING id, email, name, age, score, uuid, is_admin, api_key, created_at, updated_at\n`" + `

type CreateUserParams struct {
	Email     string
	Name      string
	Age       sql.NullInt64
	Score     float64
	Uuid      string
	IsAdmin   bool
	ApiKey    []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Email     string
	Name      string
	Age       sql.NullInt64
	Score     float64
	Uuid      string
	IsAdmin   bool
	ApiKey    []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.Age,
		arg.Score,
		arg.Uuid,
		arg.IsAdmin,
		arg.ApiKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Age,
		&i.Score,
		&i.Uuid,
		&i.IsAdmin,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = ` + "`-- name: UpdateUser :one\nUPDATE users\nSET email = $2, name = $3, age = $4, score = $5, is_admin = $6, updated_at = $7\nWHERE id = $1\nRETURNING id, email, name, age, score, uuid, is_admin, api_key, created_at, updated_at\n`" + `

type UpdateUserParams struct {
	ID        int64
	Email     string
	Name      string
	Age       sql.NullInt64
	Score     float64
	IsAdmin   bool
	UpdatedAt time.Time
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Age,
		arg.Score,
		arg.IsAdmin,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Age,
		&i.Score,
		&i.Uuid,
		&i.IsAdmin,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}`

	sqlcQueriesPath := filepath.Join(inputDir, "queries.sql.go")
	if err := os.WriteFile(sqlcQueriesPath, []byte(sqlcQueriesContent), 0644); err != nil {
		t.Fatalf("Failed to write sqlc queries file: %v", err)
	}

	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current directory: %v", err)
	}
	if err := os.Chdir(filepath.Join(tmpDir, "ent")); err != nil {
		t.Fatalf("Failed to change directory: %v", err)
	}
	defer os.Chdir(originalDir)

	sqlcWrapCommand([]string{inputDir, outputDir})

	outputPath := filepath.Join(outputDir, "queries.sql.go")
	if _, err := os.Stat(outputPath); os.IsNotExist(err) {
		t.Fatalf("Expected queries.sql.go was not created at %s", outputPath)
	}

	actualContent, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read generated queries.sql.go: %v", err)
	}

	expectedContent := `package gen

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/guntisdev/entlite/examples/01-basic-entity/ent/logic"
	"time"
	db "github.com/guntisdev/entlite/examples/01-basic-entity/ent/gen/db"
)

type DBTX = db.DBTX
var New = db.New
type Queries db.Queries
type CreateUserParams struct {
	Email string
	Name string
	Age sql.NullInt64
	Score float64
	IsAdmin bool
}

type User = db.User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	if !logic.StartsWithCapital(arg.Name) {
		return User{}, fmt.Errorf("Failed create: incorrect value for 'User' in field 'name', validated by 'logic.StartsWithCapital'")
	}
	internalArg := db.CreateUserParams{
		Email: arg.Email,
		Name: arg.Name,
		Age: arg.Age,
		Score: arg.Score,
		Uuid: logic.GetUuidStr(),
		IsAdmin: arg.IsAdmin,
		ApiKey: logic.GenerateAPIKey(),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	return (*db.Queries)(q).CreateUser(ctx, internalArg)
}

type UpdateUserParams struct {
	ID int64
	Email string
	Name string
	Age sql.NullInt64
	Score float64
	IsAdmin bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	if !logic.StartsWithCapital(arg.Name) {
		return User{}, fmt.Errorf("Failed update: incorrect value for 'User' in field 'name', validated by 'logic.StartsWithCapital'")
	}
	internalArg := db.UpdateUserParams{
		Email: arg.Email,
		Name: arg.Name,
		Age: arg.Age,
		Score: arg.Score,
		IsAdmin: arg.IsAdmin,
		UpdatedAt: time.Now(),
	}
	return (*db.Queries)(q).UpdateUser(ctx, internalArg)
}`

	if d := util.Diff(expectedContent, string(actualContent)); d != "" {
		t.Errorf("queries.sql.go content mismatch (-expected +actual):\n%s", d)
	}
}
