package docs

import (
	"fmt"
	"strings"
)

const rootReadme = "README.md"
const examplesMarker = "examples"

// readme rewrites the generated regions of the hand written readme files.
func readme(p *Pipeline) error {
	examples, err := scanExamples(p)
	if err != nil {
		return err
	}

	content, err := p.Read(rootReadme)
	if err != nil {
		return err
	}

	updated, err := replaceRegion(string(content), examplesMarker, examplesTable(examples))
	if err != nil {
		return fmt.Errorf("%s: %w", rootReadme, err)
	}
	p.Write(rootReadme, []byte(updated))

	return nil
}

func examplesTable(examples []example) string {
	rows := make([][]string, 0, len(examples))
	for _, ex := range examples {
		bullets := make([]string, 0, len(ex.Teaches))
		for _, bullet := range ex.Teaches {
			bullets = append(bullets, escapePipe(bullet))
		}
		rows = append(rows, []string{
			fmt.Sprintf("[%s](%s)", ex.Slug, ex.Path),
			strings.Join(bullets, "<br>"),
		})
	}

	notice := "<!-- generated by make docs, edit the teaches block in examples/*/README.md -->\n"

	return notice + markdownTable([]string{"Example", "Teaches"}, rows)
}
