package docs

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

const rootReadme = "README.md"
const examplesMarker = "examples"
const pagesMarker = "pages"
const generatedNotice = "<!-- generated by make docs, %s -->\n"

// rewrites the generated regions of the hand written readme files.
func readme(p *Pipeline) error {
	if err := injectExamplesTable(p); err != nil {
		return err
	}
	pages, err := injectablePages(p)
	if err != nil {
		return err
	}
	if err := injectEntTree(p, pages); err != nil {
		return err
	}
	for _, relPath := range pages {
		if err := injectSnippets(p, relPath); err != nil {
			return err
		}
	}

	return injectDocsIndex(p)
}

func injectExamplesTable(p *Pipeline) error {
	examples, err := scanExamples(p)
	if err != nil {
		return err
	}

	content, err := p.Read(rootReadme)
	if err != nil {
		return err
	}

	updated, err := replaceRegion(string(content), examplesMarker, examplesTable(examples))
	if err != nil {
		return fmt.Errorf("%s: %w", rootReadme, err)
	}
	p.Write(rootReadme, []byte(updated))

	return nil
}

func injectablePages(p *Pipeline) ([]string, error) {
	guides, err := markdownFiles(p, p.Out(guideDir))
	if err != nil {
		return nil, err
	}

	return append([]string{rootReadme, p.Out(docsIndex)}, guides...), nil
}

func examplesTable(examples []example) string {
	rows := make([][]string, 0, len(examples))
	for _, ex := range examples {
		bullets := make([]string, 0, len(ex.Teaches))
		for _, bullet := range ex.Teaches {
			bullets = append(bullets, escapePipe(bullet))
		}
		rows = append(rows, []string{
			fmt.Sprintf("[%s](%s)", ex.Slug, ex.Path),
			strings.Join(bullets, "<br>"),
		})
	}

	notice := fmt.Sprintf(generatedNotice, "edit the teaches block in examples/*/README.md")

	return notice + markdownTable([]string{"Example", "Teaches"}, rows)
}

func markdownFiles(p *Pipeline, dir string) ([]string, error) {
	found := map[string]bool{}
	for _, relPath := range p.paths() {
		if strings.HasPrefix(relPath, dir+"/") && strings.HasSuffix(relPath, ".md") {
			found[relPath] = true
		}
	}

	entries, err := os.ReadDir(p.Abs(dir))
	if err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("failed to read %s: %w", dir, err)
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		found[dir+"/"+entry.Name()] = true
	}

	files := make([]string, 0, len(found))
	for relPath := range found {
		files = append(files, relPath)
	}
	sort.Strings(files)

	return files, nil
}
