-- Code generated by entlite. DO NOT EDIT.

-- Table definitions for all entities

-- user table
CREATE TABLE "user"(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  -- Full name, e.g. "Jane Doe"
  name TEXT NOT NULL,
  age INTEGER,
  password TEXT NOT NULL,
  api_key BLOB NOT NULL,
  is_active INTEGER DEFAULT true NOT NULL,
  login_count INTEGER DEFAULT 0 NOT NULL,
  rating REAL DEFAULT 0 NOT NULL,
  -- UI preferences, e.g. {"theme":"dark"}
  preferences TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);
CREATE INDEX "idx_user_age_is_active" ON "user" (age, is_active);
CREATE INDEX "idx_user_is_active_created_at" ON "user" (is_active, created_at DESC);
CREATE UNIQUE INDEX "idx_user_name_email" ON "user" (name, email);
CREATE INDEX "idx_users_stats" ON "user" (login_count, rating);

