-- Code generated by entlite. DO NOT EDIT.

-- SQLC compatible query definitions

-- Article CRUD operations

-- name: CreateArticle :one
-- re-posting a slug keeps the article that is already there, the caller
-- gets sql.ErrNoRows because nothing was inserted
INSERT INTO "article" (
  id,
  slug,
  title,
  author,
  subtitle,
  reading_minutes,
  last_viewed_ms,
  rating,
  cover_image,
  published_at,
  metadata,
  is_featured,
  created_at,
  updated_at
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
ON CONFLICT (slug) DO NOTHING
RETURNING id;

-- name: GetArticleById :one
SELECT * FROM "article" WHERE id = ?;

-- name: GetArticleBySlug :one
SELECT * FROM "article" WHERE slug = ?;

-- name: ListArticleByAuthor :many
SELECT * FROM "article" WHERE author = @author LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: ListAllArticle :many
SELECT * FROM "article";

-- name: ListArticleFilterByAuthorIsFeaturedPublishedAtTitle :many
SELECT *, COUNT(*) OVER() AS total_size FROM "article" WHERE author = @author AND is_featured = @is_featured AND published_at >= @min_published_at AND published_at <= @max_published_at AND title LIKE @title ORDER BY published_at LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: UpdateArticle :one
UPDATE "article" SET
  slug = @slug,
  title = @title,
  author = @author,
  subtitle = @subtitle,
  reading_minutes = @reading_minutes,
  last_viewed_ms = @last_viewed_ms,
  rating = @rating,
  cover_image = @cover_image,
  published_at = @published_at,
  metadata = @metadata,
  is_featured = COALESCE(sqlc.narg('is_featured'), is_featured),
  updated_at = @updated_at
WHERE id = @id
RETURNING *;

-- name: DeleteArticle :exec
DELETE FROM "article" WHERE id = ?;

