-- Code generated by entlite. DO NOT EDIT.

-- Table definitions for all entities

-- article table
CREATE TABLE IF NOT EXISTS "article"(
  -- uuid primary key, generated on the server and not part of requests
  ID TEXT PRIMARY KEY,
  -- Human/URL identifier, e.g. hello-world
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  subtitle TEXT,
  reading_minutes INTEGER,
  last_viewed_ms INTEGER,
  rating REAL,
  cover_image BLOB,
  published_at DATETIME,
  -- Free-form metadata, e.g. {"og_image":"/cover.png"}
  metadata TEXT,
  is_featured INTEGER DEFAULT false NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);

