package parser

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/guntisdev/entlite/internal/schema"
)

// the entity has an auto generated id and a unique email
func TestParseQueryUpsert(t *testing.T) {
	tests := []struct {
		name       string
		queries    string
		wantUpsert bool
		wantFields []string
		wantIgnore bool
		wantErr    string
	}{
		{
			name:    "no upsert",
			queries: `query.Create(),`,
		},
		{
			name:       "create updates the row it collides with",
			queries:    `query.Create().Upsert("email"),`,
			wantUpsert: true,
			wantFields: []string{"email"},
		},
		{
			name:       "create bulk takes it too",
			queries:    `query.CreateBulk().Upsert("email"),`,
			wantUpsert: true,
			wantFields: []string{"email"},
		},
		{
			name:       "ignore keeps the existing row",
			queries:    `query.Create().Upsert("email").Ignore(),`,
			wantUpsert: true,
			wantFields: []string{"email"},
			wantIgnore: true,
		},
		{
			name:       "chain order does not matter",
			queries:    `query.Create().Ignore().Upsert("email"),`,
			wantUpsert: true,
			wantFields: []string{"email"},
			wantIgnore: true,
		},
		{
			name:       "name still works alongside",
			queries:    `query.Create().Upsert("email").Name("Import"),`,
			wantUpsert: true,
			wantFields: []string{"email"},
		},
		{
			name:    "ignore needs an upsert",
			queries: `query.Create().Ignore(),`,
			wantErr: "has Ignore() without Upsert()",
		},
		{
			name:    "a database generated key never collides",
			queries: `query.Create().Upsert(),`,
			wantErr: "the primary key is generated by the database and never collides",
		},
		{
			name:    "target must exist",
			queries: `query.Create().Upsert("nope"),`,
			wantErr: `Upsert references nonexisting field "nope"`,
		},
		{
			name:    "target must be unique",
			queries: `query.Create().Upsert("id", "email"),`,
			wantErr: "Upsert target (id, email) is not unique",
		},
		{
			name:    "target rejects a repeated field",
			queries: `query.Create().Upsert("email", "email"),`,
			wantErr: `Upsert repeats field "email"`,
		},
		{
			name:    "upsert takes field names",
			queries: `query.Create().Upsert(5),`,
			wantErr: "Upsert expects string field args",
		},
		{
			name:    "ignore takes nothing",
			queries: `query.Create().Upsert("email").Ignore(10),`,
			wantErr: "Ignore does not accept arguments",
		},
		{
			name:    "not a list query option",
			queries: `query.ListAll().Upsert("email"),`,
			wantErr: "Upsert is only supported for create queries",
		},
		{
			name:    "not an update option",
			queries: `query.Update().Ignore(),`,
			wantErr: "Ignore is only supported for create queries",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			entity, err := parseQueryContractEntity(t, bothContracts, test.queries)

			if test.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), test.wantErr) {
					t.Fatalf("expected error containing %q, got: %v", test.wantErr, err)
				}
				return
			}
			if err != nil {
				t.Fatalf("expected no error, got: %v", err)
			}

			query := entity.Queries[0]
			if query.Upsert != test.wantUpsert {
				t.Errorf("Upsert: expected %v, got %v", test.wantUpsert, query.Upsert)
			}
			if query.UpsertIgnore != test.wantIgnore {
				t.Errorf("UpsertIgnore: expected %v, got %v", test.wantIgnore, query.UpsertIgnore)
			}
			if !equalStrings(query.UpsertFields, test.wantFields) {
				t.Errorf("UpsertFields: expected %v, got %v", test.wantFields, query.UpsertFields)
			}
		})
	}
}

const upsertEntityTemplate = `package schema

import (
	"github.com/guntisdev/entlite/pkg/entlite"
	"github.com/guntisdev/entlite/pkg/entlite/field"
	"github.com/guntisdev/entlite/pkg/entlite/index"
	"github.com/guntisdev/entlite/pkg/entlite/query"
)

type Setting struct {
	entlite.Schema
}

func (Setting) Contracts() []entlite.Contract {
	return []entlite.Contract{
		entlite.SQLC(),
		entlite.PROTO(),
	}
}

func (Setting) Fields() []entlite.Field {
	return []entlite.Field{
		FIELDS
	}
}

func (Setting) Queries() []entlite.Query {
	return []entlite.Query{
		QUERIES
	}
}

func (Setting) Indexes() []entlite.Index {
	return []entlite.Index{
		INDEXES
	}
}
`

const defaultUpsertFields = `field.String("country"),
		field.String("env"),
		field.String("value"),`

// the conflict target may also be a unique index or a compound primary key
func TestParseQueryUpsertTarget(t *testing.T) {
	tests := []struct {
		name       string
		indexes    string
		queries    string
		wantTarget []string
		wantErr    string
	}{
		{
			name:       "unique index",
			indexes:    `index.Asc("country", "env").Unique(),`,
			queries:    `query.Create().Upsert("country", "env"),`,
			wantTarget: []string{"country", "env"},
		},
		{
			name:       "unique index in any order",
			indexes:    `index.Asc("country", "env").Unique(),`,
			queries:    `query.Create().Upsert("env", "country"),`,
			wantTarget: []string{"env", "country"},
		},
		{
			name:       "compound primary key is the default target",
			indexes:    `index.Primary("country", "env"),`,
			queries:    `query.Create().Upsert(),`,
			wantTarget: []string{"country", "env"},
		},
		{
			name:       "compound primary key named out",
			indexes:    `index.Primary("country", "env"),`,
			queries:    `query.Create().Upsert("country", "env"),`,
			wantTarget: []string{"country", "env"},
		},
		{
			name:    "a plain index is not unique",
			indexes: `index.Asc("country", "env"),`,
			queries: `query.Create().Upsert("country", "env"),`,
			wantErr: "Upsert target (country, env) is not unique",
		},
		{
			name:    "half of a unique index is not unique",
			indexes: `index.Asc("country", "env").Unique(),`,
			queries: `query.Create().Upsert("country"),`,
			wantErr: "Upsert target (country) is not unique",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			entity, err := parseUpsertEntity(t, defaultUpsertFields, test.queries, test.indexes)

			if test.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), test.wantErr) {
					t.Fatalf("expected error containing %q, got: %v", test.wantErr, err)
				}
				return
			}
			if err != nil {
				t.Fatalf("expected no error, got: %v", err)
			}

			query := entity.Queries[0]
			if !query.Upsert {
				t.Fatal("expected the query to upsert")
			}
			if got := entity.UpsertTarget(query); !equalStrings(got, test.wantTarget) {
				t.Errorf("UpsertTarget: expected %v, got %v", test.wantTarget, got)
			}
		})
	}
}

// an upsert needs a column to overwrite, unless it ignores the conflict
func TestParseQueryUpsertSetColumns(t *testing.T) {
	// slug is the target and created_at is immutable, so DO UPDATE has nothing to write
	keyAndImmutable := `field.String("slug").Unique(),
		field.Time("created_at").Immutable(),`

	tests := []struct {
		name    string
		fields  string
		queries string
		wantErr string
	}{
		{
			name:    "nothing left to update",
			fields:  keyAndImmutable,
			queries: `query.Create().Upsert("slug"),`,
			wantErr: "has Upsert() with no column left to update",
		},
		{
			name:    "ignore does not need a column",
			fields:  keyAndImmutable,
			queries: `query.Create().Upsert("slug").Ignore(),`,
		},
		{
			name:    "one plain column is enough",
			fields:  keyAndImmutable + "\n\t\tfield.String(\"title\"),",
			queries: `query.Create().Upsert("slug"),`,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := parseUpsertEntity(t, test.fields, test.queries, "")

			if test.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), test.wantErr) {
					t.Fatalf("expected error containing %q, got: %v", test.wantErr, err)
				}
				return
			}
			if err != nil {
				t.Fatalf("expected no error, got: %v", err)
			}
		})
	}
}

func parseUpsertEntity(t *testing.T, fields, queries, indexes string) (schema.Entity, error) {
	t.Helper()

	dir := t.TempDir()
	path := filepath.Join(dir, "setting.go")
	source := strings.Replace(upsertEntityTemplate, "FIELDS", fields, 1)
	source = strings.Replace(source, "QUERIES", queries, 1)
	source = strings.Replace(source, "INDEXES", indexes, 1)

	if err := os.WriteFile(path, []byte(source), 0644); err != nil {
		t.Fatalf("failed to write entity file: %v", err)
	}

	entities, err := ParseEntities([]DiscoveredEntity{{Name: "Setting", Path: path}})
	if err != nil {
		return schema.Entity{}, err
	}

	return entities[0], nil
}

func equalStrings(got, want []string) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}

	return true
}
