package util

const (
	GeneratedGo  = "// Code generated by entlite. DO NOT EDIT.\n\n"
	GeneratedSQL = "-- Code generated by entlite. DO NOT EDIT.\n\n"
	GeneratedMD  = "<!-- Code generated by entlite. DO NOT EDIT. -->\n\n"
)
